# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SJBR\SrFreecap\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  SJBR\SrFreecap\Configuration\ConfigurationHelper:
    public: true